In [240]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [241]:
data=pd.read_csv(r'C:\Users\Qin\Desktop\CODE\sale_real_estate.csv')
data['address'] = data['address'].str.replace('·\n','',regex=False)
data1=data.copy()
data1

,product_id,address,price,area,bedrooms_num,bathrooms_num
0,42142273,"Đông Anh, Hà Nội","22,96 tỷ",75 m²,0,0
1,42119145,"Đông Anh, Hà Nội","44,5 tỷ",160 m²,0,0
2,41965583,"Quận 2, Hồ Chí Minh",12 tỷ,95 m²,2,2
3,42142105,"Văn Giang, Hưng Yên","12,7 tỷ","87,5 m²",5,5
4,41621659,"Văn Giang, Hưng Yên","14,3 tỷ",84 m²,0,0
...,...,...,...,...,...,...
42252,40122861,"Quận 8, Hồ Chí Minh","1,9 tỷ",50 m²,1,1
42253,40652968,"Quận 7, Hồ Chí Minh","26,5 tỷ",175 m²,0,0
42254,42067403,"Quận 7, Hồ Chí Minh",110 tỷ,"252,38 m²",0,0
42255,41917028,"Long Đất, Bà Rịa Vũng Tàu",800 triệu,1.000 m²,0,0
42256,39864373,"Hai Bà Trưng, Hà Nội",42 tỷ,158 m²,0,0

In [242]:
print(data.duplicated().sum())
data1=data.drop_duplicates()
data1.info()

2337
<class 'pandas.DataFrame'>
Index: 39920 entries, 0 to 42256
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     39920 non-null  int64
 1   address        39920 non-null  str
 2   price          39920 non-null  str
 3   area           39920 non-null  str
 4   bedrooms_num   39920 non-null  int64
 5   bathrooms_num  39920 non-null  int64
dtypes: int64(3), str(3)
memory usage: 2.1 MB

In [243]:
len(data['address'].unique())

421

In [244]:
address_stats=data.groupby('address')['address'].agg('count').sort_values(ascending=False)
address_stats

address
Hà Đông, Hà Nội            1598
Quận 2, Hồ Chí Minh        1567
Nam Từ Liêm, Hà Nội        1487
Quận 7, Hồ Chí Minh        1423
Quận 9, Hồ Chí Minh        1361
                           ...
Đoan Hùng, Phú Thọ            1
Ea H'Leo, Đắk Lắk             1
Châu Thành A, Hậu Giang       1
Vĩnh Bảo, Hải Phòng           1
Ba Đồn, Quảng Bình            1
Name: address, Length: 421, dtype: int64

In [245]:
len(address_stats[address_stats<10])

220

In [246]:
address_stats_less_than_10=address_stats[address_stats<10]
address_stats_less_than_10

address
Phú Thọ, Phú Thọ           9
Di Linh, Lâm Đồng          9
Bình Thủy, Cần Thơ         9
Cẩm Phả, Quảng Ninh        9
Yên Phong, Bắc Ninh        9
                          ..
Đoan Hùng, Phú Thọ         1
Ea H'Leo, Đắk Lắk          1
Châu Thành A, Hậu Giang    1
Vĩnh Bảo, Hải Phòng        1
Ba Đồn, Quảng Bình         1
Name: address, Length: 220, dtype: int64

In [247]:
data1.address=data1.address.apply(lambda x:'other' if x in address_stats_less_than_10 else x)

In [248]:

len(data1['price'].astype(str).str.isalpha())
data1

,product_id,address,price,area,bedrooms_num,bathrooms_num
0,42142273,"Đông Anh, Hà Nội","22,96 tỷ",75 m²,0,0
1,42119145,"Đông Anh, Hà Nội","44,5 tỷ",160 m²,0,0
2,41965583,"Quận 2, Hồ Chí Minh",12 tỷ,95 m²,2,2
3,42142105,"Văn Giang, Hưng Yên","12,7 tỷ","87,5 m²",5,5
4,41621659,"Văn Giang, Hưng Yên","14,3 tỷ",84 m²,0,0
...,...,...,...,...,...,...
42252,40122861,"Quận 8, Hồ Chí Minh","1,9 tỷ",50 m²,1,1
42253,40652968,"Quận 7, Hồ Chí Minh","26,5 tỷ",175 m²,0,0
42254,42067403,"Quận 7, Hồ Chí Minh",110 tỷ,"252,38 m²",0,0
42255,41917028,"Long Đất, Bà Rịa Vũng Tàu",800 triệu,1.000 m²,0,0
42256,39864373,"Hai Bà Trưng, Hà Nội",42 tỷ,158 m²,0,0

In [249]:
data1['price']=data1['price'].str.replace('.','').str.replace(',','.')

In [250]:
def convert_number(price):
    if pd.isna(price):
        return None
    price=price.strip()
    if 'tỉ' in price or 'tỷ' in price:
        price=price.replace('tỉ','').replace('tỷ','')
        return float(price.strip().replace(',', '.')) * 1_000_000_000
    elif 'triệu' in price:
        price=price.replace('triệu','')
        return float(price.replace('triệu',''))*1000000
data1['price']=data1['price'].apply(convert_number)
data1

,product_id,address,price,area,bedrooms_num,bathrooms_num
0,42142273,"Đông Anh, Hà Nội",2.296000e+10,75 m²,0,0
1,42119145,"Đông Anh, Hà Nội",4.450000e+10,160 m²,0,0
2,41965583,"Quận 2, Hồ Chí Minh",1.200000e+10,95 m²,2,2
3,42142105,"Văn Giang, Hưng Yên",1.270000e+10,"87,5 m²",5,5
4,41621659,"Văn Giang, Hưng Yên",1.430000e+10,84 m²,0,0
...,...,...,...,...,...,...
42252,40122861,"Quận 8, Hồ Chí Minh",1.900000e+09,50 m²,1,1
42253,40652968,"Quận 7, Hồ Chí Minh",2.650000e+10,175 m²,0,0
42254,42067403,"Quận 7, Hồ Chí Minh",1.100000e+11,"252,38 m²",0,0
42255,41917028,"Long Đất, Bà Rịa Vũng Tàu",8.000000e+08,1.000 m²,0,0
42256,39864373,"Hai Bà Trưng, Hà Nội",4.200000e+10,158 m²,0,0

In [251]:
data1['area']=data1['area'].str.replace('m²','').str.replace('.','').str.replace(',','.')
data1['area']=data1['area'].astype(float)
data1

,product_id,address,price,area,bedrooms_num,bathrooms_num
0,42142273,"Đông Anh, Hà Nội",2.296000e+10,75.00,0,0
1,42119145,"Đông Anh, Hà Nội",4.450000e+10,160.00,0,0
2,41965583,"Quận 2, Hồ Chí Minh",1.200000e+10,95.00,2,2
3,42142105,"Văn Giang, Hưng Yên",1.270000e+10,87.50,5,5
4,41621659,"Văn Giang, Hưng Yên",1.430000e+10,84.00,0,0
...,...,...,...,...,...,...
42252,40122861,"Quận 8, Hồ Chí Minh",1.900000e+09,50.00,1,1
42253,40652968,"Quận 7, Hồ Chí Minh",2.650000e+10,175.00,0,0
42254,42067403,"Quận 7, Hồ Chí Minh",1.100000e+11,252.38,0,0
42255,41917028,"Long Đất, Bà Rịa Vũng Tàu",8.000000e+08,1000.00,0,0
42256,39864373,"Hai Bà Trưng, Hà Nội",4.200000e+10,158.00,0,0

In [252]:
data1['price_per_sqmt']=data1['price']/data1['area']
data1

,product_id,address,price,area,bedrooms_num,bathrooms_num,price_per_sqmt
0,42142273,"Đông Anh, Hà Nội",2.296000e+10,75.00,0,0,3.061333e+08
1,42119145,"Đông Anh, Hà Nội",4.450000e+10,160.00,0,0,2.781250e+08
2,41965583,"Quận 2, Hồ Chí Minh",1.200000e+10,95.00,2,2,1.263158e+08
3,42142105,"Văn Giang, Hưng Yên",1.270000e+10,87.50,5,5,1.451429e+08
4,41621659,"Văn Giang, Hưng Yên",1.430000e+10,84.00,0,0,1.702381e+08
...,...,...,...,...,...,...,...
42252,40122861,"Quận 8, Hồ Chí Minh",1.900000e+09,50.00,1,1,3.800000e+07
42253,40652968,"Quận 7, Hồ Chí Minh",2.650000e+10,175.00,0,0,1.514286e+08
42254,42067403,"Quận 7, Hồ Chí Minh",1.100000e+11,252.38,0,0,4.358507e+08
42255,41917028,"Long Đất, Bà Rịa Vũng Tàu",8.000000e+08,1000.00,0,0,8.000000e+05
42256,39864373,"Hai Bà Trưng, Hà Nội",4.200000e+10,158.00,0,0,2.658228e+08

In [253]:
data1.price_per_sqmt.describe()

count    3.588200e+04
mean     1.275341e+08
std      1.790907e+08
min      1.000000e+03
25%      4.193124e+07
50%      7.981263e+07
75%      1.699408e+08
max      1.620000e+10
Name: price_per_sqmt, dtype: float64

In [254]:
def remove_pps_outliers(data1):
    data_out=pd.DataFrame()
    for key, subdata in data1.groupby('area'):
        m=np.mean(subdata.price_per_sqmt)
        st=np.std(subdata.price_per_sqmt)
        reduced_data=subdata[(subdata.price_per_sqmt>(m-st))&(subdata.price_per_sqmt<=(m+st))]
        data_out=pd.concat([data_out,reduced_data],ignore_index=True)
    return data_out
data1=remove_pps_outliers(data1)
data1.shape

(27839, 7)

In [255]:
data1.price_per_sqmt.describe()

count    2.783900e+04
mean     9.756357e+07
std      8.181939e+07
min      2.900000e+04
25%      4.400000e+07
50%      7.476636e+07
75%      1.386667e+08
max      3.086420e+09
Name: price_per_sqmt, dtype: float64